version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: '@nx/*'
      - dependency-name: '@material/*'
      - dependency-name: 'material-components-web'
    target-branch: 'next'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: '@nx/*'    
      - dependency-name: '@material/*'
      - dependency-name: 'material-components-web'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
