name: RMWC Release

on:
  pull_request:
    branches: [master, next]
    types: [opened, reopened]

jobs:
  release:
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'release/')
    steps:
      - uses: actions/checkout@v2
      - name: Setup Git
        run: git fetch origin ${{ github.head_ref }} && git checkout ${{ github.head_ref }}
      - run: git config --global user.email "ci@rmwc.io"
      - run: git config --global user.name "RMWC CI"
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - name: 'Patch Release'
        run: npm run release:patch
        if: contains(github.head_ref, '/patch') && github.base_ref == 'master'
      - name: 'Minor Release'
        run: npm run release:minor
        if: contains(github.head_ref, '/minor') && github.base_ref == 'master'
      - name: 'Major Release'
        run: npm run release:major
        if: contains(github.head_ref, '/major') && github.base_ref == 'master'
      - name: 'Alpha Patch Release'
        run: npm run alpha:patch
        if: contains(github.head_ref, '/patch') && github.base_ref == 'next'
      - name: 'Alpha Minor Release'
        run: npm run alpha:minor
        if: contains(github.head_ref, '/minor') && github.base_ref == 'next'
      - name: 'Alpha Major Release'
        run: npm run alpha:major
        if: contains(github.head_ref, '/major') && github.base_ref == 'next'
